"""CLI entry point for EKS Scout."""
import argparse
import logging
import sys
from datetime import datetime

from eks_scout.scanner import scan
from eks_scout.config import SEVERITY_RANK
from eks_scout.reporting.csv_export import export_findings_to_csv
from eks_scout.reporting.json_export import export_findings_to_json
from eks_scout.reporting.console import print_summary

BANNER = r'''
 ______       ___   ___      ______                     ______       ______       ______       __  __       _________
/_____/\     /___/\/__/\    /_____/\                   /_____/\     /_____/\     /_____/\     /_/\/_/\     /________/\
\::::_\/_    \::.\ \\ \ \   \::::_\/_       _______    \::::_\/_    \:::__\/     \:::_ \ \    \:\ \:\ \    \__.::.__\/
 \:\/___/\    \:: \/_) \ \   \:\/___/\     /______/\    \:\/___/\    \:\ \  __    \:\ \ \ \    \:\ \:\ \      \::\ \
  \::___\/_    \:. __  ( (    \_::._\:\    \__::::\/     \_::._\:\    \:\ \/_/\    \:\ \ \ \    \:\ \:\ \      \::\ \
   \:\____/\    \: \ )  \ \     /____\:\                   /____\:\    \:\_\ \ \    \:\_\ \ \    \:\_\:\ \      \::\ \
    \_____\/     \__\/\__\/     \_____\/                   \_____\/     \_____\/     \_____\/     \_____\/       \__\/
'''


def cmd_scan(args):
    """Execute the scan subcommand."""
    print(BANNER)

    start_time = datetime.now()
    logging.info(f"Starting EKS Scout scan for cluster '{args.cluster_name}' in region '{args.region}'...")
    logging.info(f"Using AWS Profile: '{args.profile or 'default'}' | Using kubectl Context: '{args.context or 'default'}'")
    logging.info("NOTE: This tool uses read-only kubectl and aws cli commands.")

    result = scan(
        cluster_name=args.cluster_name,
        region=args.region,
        profile=args.profile,
        context=args.context,
        config_file=args.config,
        show_suppressed=getattr(args, 'show_suppressed', False),
    )

    if result is None:
        logging.error("Scan aborted due to dependency check failure.")
        sys.exit(1)

    end_time = datetime.now()
    duration = end_time - start_time
    logging.info(f"--- Scan Complete (duration: {duration}) ---")

    if not result.findings and not result.suppressed:
        logging.info("No specific security issues found based on the current checks.")
        return

    # Print console summary
    print_summary(result.findings, suppressed_count=result.suppressed_count,
                  combos=result.combos, duration=duration)

    # Export results (active findings, plus suppressed if --show-suppressed)
    export_findings = result.all_findings
    output_file = args.output_file
    if args.output_format == 'csv':
        export_findings_to_csv(export_findings, output_file)
    elif args.output_format == 'json':
        export_findings_to_json(export_findings, output_file, combos=result.combos)

    # CI/CD exit code gating
    fail_on = getattr(args, 'fail_on', None)
    if fail_on:
        threshold = SEVERITY_RANK[fail_on.capitalize()]
        for finding in result.findings:
            finding_rank = SEVERITY_RANK.get(finding.get('severity', ''), 99)
            if finding_rank <= threshold:
                logging.error(f"Failing: found finding with severity '{finding['severity']}' "
                              f"(threshold: {fail_on})")
                sys.exit(2)
        logging.info(f"No findings at or above '{fail_on}' severity. Exiting 0.")


def cmd_init(args):
    """Generate a default configuration file."""
    import os

    output = args.output or "eks-scout.yaml"
    if os.path.exists(output) and not args.force:
        print(f"Config file '{output}' already exists. Use --force to overwrite.")
        sys.exit(1)

    config_content = _generate_default_config()
    with open(output, 'w') as f:
        f.write(config_content)
    print(f"Generated default configuration file: {output}")
    print("Edit this file to customize checks, suppressions, and settings.")


def _generate_default_config():
    """Generate a well-commented default YAML config."""
    return """# EKS Scout Configuration File
# Generated by: eks-scout init
# Documentation: https://github.com/amberg/eks-scout

# Enable or disable specific checks.
# Use check IDs (e.g., "k8s.pods") or "*" as wildcard.
checks:
  "*": true
  # Examples:
  # "k8s.pods": true
  # "k8s.rbac": true
  # "aws.cluster": true
  # "aws.nodegroups": true

# Override default severity levels for specific checks.
# severity_overrides:
#   "k8s.pods.latest-tag": "Medium"
#   "k8s.pods.may-run-as-root": "Informational"

# Suppressions — reduce false positives by excluding known-good findings.
# Each rule can match by type, namespace, name (regex), or labels.
suppressions: []
  # Examples:
  #
  # Suppress all findings in kube-system:
  # - namespace: "kube-system"
  #   reason: "System namespace - expected configuration"
  #
  # Suppress a specific finding type globally:
  # - type: "Container May Run As Root"
  #   reason: "Accepted risk for legacy workloads"
  #
  # Suppress by namespace + finding type:
  # - namespace: "monitoring"
  #   type: "Service Exposed via LoadBalancer"
  #   reason: "Intentional external exposure for Grafana"
  #
  # Suppress by resource name pattern (regex):
  # - name: "datadog-.*"
  #   reason: "Datadog agent requires host access"

# Custom settings — override hardcoded defaults.
settings:
  psa_expected_level: "restricted"

  allowed_registries:
    - "amazonaws.com"
    - "docker.io"
    - "gcr.io"
    - "quay.io"
    - "ghcr.io"
    - "mcr.microsoft.com"

  sensitive_hostpaths:
    - "/"
    - "/etc"
    - "/var"
    - "/usr"
    - "/proc"
    - "/root"
    - "/var/run/docker.sock"

  sensitive_key_patterns:
    - "password"
    - "secret"
    - "token"
    - "key"
    - "passwd"
    - "pwd"
    - "auth"
    - "credential"
    - "apikey"
    - "access_key"
    - "secret_key"

  system_namespaces:
    - "kube-system"
    - "kube-public"
    - "kube-node-lease"
"""


def main():
    """Main CLI entry point."""
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

    parser = argparse.ArgumentParser(
        prog="eks-scout",
        description="EKS Scout - Passive Security Scanner for AWS EKS"
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # --- scan subcommand ---
    scan_parser = subparsers.add_parser("scan", help="Run a security scan against an EKS cluster")
    scan_parser.add_argument("--cluster-name", required=True, help="Name of the EKS cluster")
    scan_parser.add_argument("--region", required=True, help="AWS region of the EKS cluster")
    scan_parser.add_argument("--profile", help="AWS CLI profile to use")
    scan_parser.add_argument("--context", help="kubectl context to use")
    scan_parser.add_argument("-o", "--output-file", default="eks_findings_plextrac.csv",
                             help="Output file name (default: eks_findings_plextrac.csv)")
    scan_parser.add_argument("-f", "--output-format", choices=['csv', 'json'], default='csv',
                             help="Output format (default: csv)")
    scan_parser.add_argument("--config", help="Path to configuration file (YAML or JSON)")
    scan_parser.add_argument("--show-suppressed", action="store_true",
                             help="Include suppressed findings in output with 'Suppressed' status")
    scan_parser.add_argument("--debug", action="store_true", help="Enable debug logging")
    scan_parser.add_argument("--fail-on", choices=['critical', 'high', 'medium', 'low'],
                             help="Exit with code 2 if any finding meets or exceeds this severity (for CI/CD gating)")

    # --- init subcommand ---
    init_parser = subparsers.add_parser("init", help="Generate a default configuration file")
    init_parser.add_argument("-o", "--output", help="Output file path (default: eks-scout.yaml)")
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing config file")

    args = parser.parse_args()

    if args.command == "scan":
        if args.debug:
            logging.getLogger().setLevel(logging.DEBUG)
        cmd_scan(args)
    elif args.command == "init":
        cmd_init(args)
    else:
        parser.print_help()
        sys.exit(1)
